namespace TestComponent
{
    [default_interface]
    runtimeclass Class
    {
        Class();

        void ShowMessage(String message);
        void ShowMessage(String message, Microsoft.UI.WindowId windowId);
    }
}
